services:
  victorialogs:
    image: victoriametrics/victoria-logs:latest
    container_name: victorialogs
    restart: unless-stopped
    ports:
      - "9428:9428"
    volumes:
      - /mnt/user/victorialogs:/victoria-logs-data
    command:
      - -storageDataPath=/victoria-logs-data
      - -retentionPeriod=1M
